// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type CartItem struct {
	CartItemID int       `gorm:"column:cart_item_id;type:int(11);primary_key;AUTO_INCREMENT" json:"cart_item_id"`
	CartID     int       `gorm:"column:cart_id;type:int(11);NOT NULL" json:"cart_id"`
	ProductID  int       `gorm:"column:product_id;type:int(11);NOT NULL" json:"product_id"`
	Quantity   int       `gorm:"column:quantity;type:int(11);NOT NULL" json:"quantity"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

func (m *CartItem) TableName() string {
	return "cart_item"
}

