// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type Cart struct {
	CartID     int       `gorm:"column:cart_id;type:int(11);primary_key;AUTO_INCREMENT" json:"cart_id"`
	CustomerID int       `gorm:"column:customer_id;type:int(11);NOT NULL" json:"customer_id"`
	CartName   string    `gorm:"column:cart_name;type:varchar(255)" json:"cart_name"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

func (m *Cart) TableName() string {
	return "cart"
}

