package model


// Code generated by sql2gorm. DO NOT EDIT.

import (
	"time"
)

type Customer struct {
	CustomerID  int       `gorm:"column:customer_id;type:int(11);primary_key;AUTO_INCREMENT" json:"customer_id"`
	FirstName   string    `gorm:"column:first_name;type:varchar(255);NOT NULL" json:"first_name"`
	LastName    string    `gorm:"column:last_name;type:varchar(255);NOT NULL" json:"last_name"`
	Email       string    `gorm:"column:email;type:varchar(255);NOT NULL" json:"email"`
	PhoneNumber string    `gorm:"column:phone_number;type:varchar(20)" json:"phone_number"`
	Address     string    `gorm:"column:address;type:varchar(255)" json:"address"`
	Password    string    `gorm:"column:password;type:varchar(255);NOT NULL" json:"password"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

func (m *Customer) TableName() string {
	return "customer"
}

