// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type Product struct {
	ProductID     int       `gorm:"column:product_id;type:int(11);primary_key;AUTO_INCREMENT" json:"product_id"`
	ProductName   string    `gorm:"column:product_name;type:varchar(255);NOT NULL" json:"product_name"`
	Description   string    `gorm:"column:description;type:text" json:"description"`
	Price         string    `gorm:"column:price;type:decimal(10,2);NOT NULL" json:"price"`
	StockQuantity int       `gorm:"column:stock_quantity;type:int(11);NOT NULL" json:"stock_quantity"`
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

func (m *Product) TableName() string {
	return "product"
}

